apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeserver
  template:
    metadata:
      labels:
        app: kubeserver
    spec:
      containers:
      - name: kubecontainer
        image: damian1112/platypusbackend
        ports:
          - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        imagePullPolicy: Always